import React, { useState } from "react";
import { ArrowRight, Clock, User, X, Calendar, Share2, MessageSquare } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import ScrollReveal from "@/components/ScrollReveal";

interface BlogPost {
  id: number;
  category: string;
  title: string;
  excerpt: string;
  content: string[];
  author: string;
  readTime: string;
  image: string;
  date: string;
}

const blogPosts: BlogPost[] = [
  {
    id: 1,
    category: "Innovation",
    title: "India Built Its First 3D Printed School in 60 Days. Here Is Why That Changes Everything.",
    excerpt: "In November 2023, a fire broke out in Pachin... Eight weeks later, India had its first 3D printed school. Not a prototype, but a functioning reality.",
    date: "July 30, 2024",
    content: [
      "In November 2023, a fire broke out in a house near the Government Secondary School in Pachin, Itanagar, Arunachal Pradesh. The flames spread quickly, gutting nine classrooms and destroying every piece of furniture and electrical equipment the school had.",
      "Rather than going through the usual slow, expensive, paper-heavy process of government reconstruction, the administration chose 3D printing technology. Eight weeks later, India had its first 3D printed school. Not a prototype. Not a pilot. A functioning government school.",
      "3D printing in construction, also called additive manufacturing, works by using a large robotic printer to deposit material in precise, programmed layers. The printer follows a digital blueprint, laying down concrete one layer at a time.",
      "Unlike conventional construction, there are no moulds, no formwork, and significantly less manual labour involved. The structure is built exactly as designed, with no material wasted and no human error in execution.",
      "At TIQ, we work at the intersection of construction and interior delivery. As structures become faster and more precise to build, interior execution needs to match that pace. Modular interiors and factory-finished components are the future."
    ],
    author: "Ar. Preetha",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80"
  },
  {
    id: 2,
    category: "Design Trends",
    title: "Parametric Design Is Quietly Changing the Way Interiors Are Built.",
    excerpt: "Parametric design is a design process where the outcome is generated by rules, relationships and mathematical parameters.",
    date: "April 12, 2026",
    content: [
      "Parametric design is a design process where the outcome is generated by rules, relationships and mathematical parameters rather than by hand-drawn sketches alone. Instead of designing a fixed object, a parametric designer builds a system.",
      "Think of it this way. In traditional design, if you decide to change the angle of a ceiling panel, you redraw it manually. In parametric design, you change the angle in the system and every related element updates instantly.",
      "Parametric interior design appears most visibly in wall and ceiling panels, custom furniture, and lighting design. It allows for ripple effects and geometric patterns that respond to the room's proportions.",
      "At TIQ, our computational design capability set us apart. We use these tools to optimise spaces before execution begins, connecting directly to our in-house manufacturing units for extreme precision."
    ],
    author: "Ar. Uthresh",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80"
  },
  {
    id: 3,
    category: "Interior Tips",
    title: "Interior Design Trends in 2026: What Is Actually Worth Your Attention",
    excerpt: "Every year, design publications release lists of trends. Most of them are recycled. Here is what is actually happening in 2026.",
    date: "March 15, 2026",
    content: [
      "The cool gray and white interior has dominated for a decade. In 2026, it is giving way to warmer, earthier tones like terracotta, warm beige, and soft olive green. These tones photograph better and feel more welcoming.",
      "Textured wall finishes are replacing paint. Microcement, Venetian plaster, and fabric wall treatments create depth and absorb light differently throughout the day.",
      "Integrated storage is everywhere. Floor-to-ceiling built-ins and under-stair storage systems that disappear into the architecture are the new standard.",
      "Muted Luxury is the direction. Luxury is now expressed through material quality and craftsmanship rather than through volume and ornamentation. Brushed brass over shiny gold, honed stone over polished marble."
    ],
    author: "Ar. Mohamed Ajmaludeen",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80"
  },
  {
    id: 4,
    category: "Execution",
    title: "Why Customised Furniture Is the Smartest Investment You Can Make in Your Home",
    excerpt: "Ready-made furniture is designed for an average room. But there is no such thing as an average room. Custom is the power.",
    date: "February 28, 2026",
    content: [
      "Ready-made furniture is designed for an average room. But there is no such thing as an average room. Every home has slightly different heights, lengths and corners. Customised furniture starts with your space.",
      "Beyond fit, customised furniture gives you complete control over materials, finishes, and internal organisation. The wardrobe that fits exactly 47 pairs of shoes is the difference between storage that works and storage that frustrates.",
      "At TIQ, we manufacture everything in-house. We use graded materials exclusively and have a zero MDF policy. This ensures consistency and durability that outsourced workshops cannot match.",
      "A custom modular kitchen is the biggest win. It is designed around how you cook, how tall your family members are, and where you store what."
    ],
    author: "Ar. Preetha",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80"
  },
  {
    id: 5,
    category: "Industry",
    title: "The Rise of Smart Materials in Residential Architecture",
    excerpt: "Exploring how self-healing concrete and thermo-chromic glass are redefining modern Indian homes in 2026.",
    date: "May 05, 2026",
    content: [
      "Smart materials are no longer experimental. We are seeing self-healing concrete that uses bacteria to seal cracks and thermo-chromic glass that adjusts tint based on sunlight intensity.",
      "These materials reduce maintenance costs and improve energy efficiency. In the Indian context, where cooling is a major expense, smart glass is becoming a standard in luxury villas.",
      "At TIQ, we integrate these innovations into our execution. We research and source materials that offer longevity and performance, ensuring your home remains modern for decades."
    ],
    author: "Ar. Mohamed Ajmaludeen",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"
  }
];

const Blog = () => {
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);

  const openPost = (post: BlogPost) => {
    setSelectedPost(post);
    document.body.style.overflow = 'hidden';
  };

  const closePost = () => {
    setSelectedPost(null);
    document.body.style.overflow = 'auto';
  };

  return (
    <div className="bg-white min-h-screen pt-40 pb-24 text-[#002121]">
      <div className="container mx-auto px-6">
        {/* Header - Refined Architectural UI */}
        <div className="mb-32 relative">
          <ScrollReveal>
             <div className="flex flex-col md:flex-row items-start md:items-end justify-between gap-12">
                <div className="max-w-3xl">
                  <div className="flex items-center gap-4 mb-8">
                     
                     <p className="text-[#002121] text-[11px] font-black tracking-[0.5em] uppercase">Discovery & Innovation</p>
                  </div>
                  <h1 className="text-5xl sm:text-6xl md:text-9xl font-sans font-light tracking-tighter leading-[0.85] text-[#002121]">
                    The <br />
                    <span className="font-bold relative">
                      Journal
                      <motion.span 
                        initial={{ width: 0 }}
                        whileInView={{ width: '100%' }}
                        className="absolute -bottom-2 md:-bottom-4 left-0 h-1 md:h-2 bg-[#d89a5b]"
                      />
                    </span>
                  </h1>
                </div>
                <div className="max-w-sm ml-auto md:text-right">
                   <p className="text-gray-400 text-lg font-light leading-relaxed border-t md:border-t-0 md:border-r-4 border-[#965b32]/20 pt-8 md:pt-0 md:pr-10">
                    Exploring the convergence of computational design, advanced manufacturing, and residential lifestyle.
                   </p>
                </div>
             </div>
          </ScrollReveal>
        </div>

        {/* Grid Layout - 100% Matching "Package Offers" Premium Aesthetic */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 mb-24">
          
          {/* Featured Post (Big Box) */}
          <div className="lg:col-span-7">
            <ScrollReveal direction="left">
              <div 
                onClick={() => openPost(blogPosts[0])}
                className="bg-white group cursor-pointer overflow-hidden rounded-none border border-gray-100 h-full flex flex-col shadow-2xl hover:border-[#d89a5b]/40 transition-all duration-700"
              >
                <div className="relative aspect-[16/10] overflow-hidden">
                  <img 
                    src={blogPosts[0].image} 
                    alt={blogPosts[0].title} 
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-1000"
                  />
                  <div className="absolute inset-0 bg-[#002121]/5 group-hover:bg-transparent transition-colors" />
                </div>
                <div className="p-6 sm:p-8 md:p-12 flex-1 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-4 mb-8">
                       <span className="w-10 h-[1px] bg-[#965b32] opacity-40" />
                       <p className="text-[#965b32] text-[10px] font-bold tracking-[0.4em] uppercase">{blogPosts[0].category}</p>
                    </div>
                    <h2 className="text-[28px] sm:text-3xl md:text-5xl font-sans font-light leading-[1.1] mb-6 md:mb-8 tracking-tighter group-hover:text-[#965b32] transition-colors">
                      {blogPosts[0].title}
                    </h2>
                    <p className="text-gray-500 text-base md:text-lg leading-relaxed mb-8 md:mb-10 font-light opacity-80">
                      {blogPosts[0].excerpt}
                    </p>
                  </div>
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 sm:gap-0 pt-6 md:pt-10 border-t border-gray-50">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 rounded-none bg-[#002121] flex items-center justify-center text-xs font-bold text-white group-hover:bg-[#965b32] transition-colors">
                        {blogPosts[0].author.split(' ').pop()?.charAt(0)}
                      </div>
                      <div className="flex flex-col">
                        <span className="text-[11px] font-black text-[#002121] uppercase tracking-[0.2em]">{blogPosts[0].author}</span>
                        <span className="text-[9px] text-gray-400 font-bold uppercase tracking-widest mt-1">{blogPosts[0].readTime}</span>
                      </div>
                    </div>
                    <div className="w-14 h-14 border border-gray-100 flex items-center justify-center group-hover:bg-[#002121] transition-all shrink-0">
                       <ArrowRight className="w-5 h-5 text-[#965b32] group-hover:text-white transition-colors" />
                    </div>
                  </div>
                </div>
              </div>
            </ScrollReveal>
          </div>

          {/* Right Two Stacked */}
          <div className="lg:col-span-5 flex flex-col gap-10">
            {blogPosts.slice(1, 3).map((post, i) => (
              <ScrollReveal key={post.id} direction="right" delay={i * 0.1}>
                <div 
                  onClick={() => openPost(post)}
                  className="bg-white group cursor-pointer overflow-hidden rounded-none border border-gray-100 flex flex-col h-full shadow-2xl hover:border-[#d89a5b]/40 transition-all duration-700"
                >
                   <div className="relative aspect-[16/8] overflow-hidden">
                    <img 
                      src={post.image} 
                      alt={post.title} 
                      className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-1000"
                    />
                    <div className="absolute inset-0 bg-[#002121]/5 group-hover:bg-transparent transition-colors" />
                  </div>
                  <div className="p-6 sm:p-8 md:p-10 flex-1 flex flex-col justify-between">
                    <div>
                      <p className="text-[#965b32] text-[10px] font-bold tracking-[0.4em] uppercase mb-4">{post.category}</p>
                      <h3 className="text-xl md:text-2xl font-sans font-light leading-snug mb-6 group-hover:text-[#965b32] transition-colors tracking-tight">
                        {post.title}
                      </h3>
                    </div>
                    <div className="flex items-center gap-4 text-gray-400 text-[10px] font-bold uppercase tracking-widest border-l-2 border-[#965b32]/20 pl-4">
                       <span>{post.author}</span>
                       <span className="w-1 h-1 rounded-full bg-gray-200" />
                       <span>{post.readTime}</span>
                    </div>
                  </div>
                </div>
              </ScrollReveal>
            ))}
          </div>

          {/* Bottom Two Big Canvas */}
          {blogPosts.slice(3, 5).map((post, i) => (
            <div key={post.id} className="lg:col-span-6">
               <ScrollReveal delay={0.2 + i * 0.1}>
                 <div 
                  onClick={() => openPost(post)}
                  className="bg-white group cursor-pointer overflow-hidden rounded-none border border-gray-100 flex flex-col h-full shadow-2xl hover:border-[#d89a5b]/40 transition-all duration-700"
                 >
                    <div className="relative aspect-[21/9] overflow-hidden">
                      <img 
                        src={post.image} 
                        alt={post.title} 
                        className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-1000"
                      />
                      <div className="absolute inset-0 bg-[#002121]/5 group-hover:bg-transparent transition-colors" />
                    </div>
                    <div className="p-6 sm:p-8 md:p-12 flex-1 flex flex-col justify-between">
                       <div>
                         <p className="text-[#965b32] text-[10px] font-bold tracking-[0.4em] uppercase mb-4">{post.category}</p>
                         <h3 className="text-[24px] md:text-3xl font-sans font-light leading-snug mb-8 group-hover:text-[#965b32] transition-colors tracking-tighter">
                           {post.title}
                         </h3>
                       </div>
                       <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 sm:gap-0 pt-6 md:pt-8 border-t border-gray-100">
                          <span className="text-[11px] text-gray-400 font-bold uppercase tracking-[0.2em]">{post.readTime}</span>
                          <div className="flex items-center justify-center gap-4 bg-[#002121] text-white px-6 py-4 md:px-8 md:py-4 text-[11px] font-black uppercase tracking-widest group-hover:bg-[#965b32] transition-colors w-full sm:w-auto">
                            Read Article <ArrowRight size={14} />
                          </div>
                       </div>
                    </div>
                 </div>
               </ScrollReveal>
            </div>
          ))}
        </div>

        {/* Newsletter / CTA Section - Perfectly Matched Height & ALIGNMENT */}
        <ScrollReveal>
          <div className="bg-[#002121] rounded-none p-8 py-16 md:p-32 relative overflow-hidden text-center shadow-[0_50px_100px_rgba(0,0,0,0.15)] border border-white/5">
            <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(#d89a5b 0.5px, transparent 0.5px)', backgroundSize: '30px 30px' }} />
            
            <div className="relative z-10">
              <h2 className="text-3xl sm:text-4xl md:text-8xl font-sans font-light text-white mb-6 md:mb-8 tracking-tighter leading-tight">
                Let's <span className="font-bold">Work Together</span>
              </h2>
              <p className="text-white/40 mb-12 md:mb-16 text-sm sm:text-lg md:text-xl font-light tracking-[0.2em] md:tracking-[0.4em] max-w-2xl mx-auto leading-relaxed uppercase">
                Ready to transform your space
              </p>

              <div className="max-w-2xl mx-auto flex flex-col items-center w-full">
                <button 
                  onClick={() => window.dispatchEvent(new CustomEvent("openConsultation"))}
                  className="bg-[#d89a5b] text-white px-8 py-5 w-full sm:w-auto sm:px-16 sm:py-6 rounded-none font-black tracking-[0.2em] md:tracking-[0.4em] uppercase transition-all duration-500 hover:bg-white hover:text-[#002121] shadow-2xl text-[11px] md:text-base"
                >
                  Get My Free Consultation
                </button>
                <p className="text-white/20 text-[9px] font-bold tracking-widest uppercase mt-6">
                  Limited Spots Available for April 2026
                </p>
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>

      {/* POPUP Modal - Replicating Package Offers Style Perfectly */}
      <AnimatePresence>
        {selectedPost && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-0 md:p-10">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={closePost}
              className="absolute inset-0 bg-[#002121]/95 backdrop-blur-xl"
            />

            <motion.div
              initial={{ opacity: 0, y: 100 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 100 }}
              transition={{ type: "spring", damping: 30, stiffness: 200 }}
              className="relative w-full max-w-7xl h-full md:h-auto md:max-h-[92vh] bg-white shadow-3xl overflow-hidden flex flex-col rounded-none"
            >
              <button
                onClick={closePost}
                className="absolute top-4 right-4 md:top-10 md:right-10 z-[110] w-10 h-10 md:w-12 md:h-12 flex items-center justify-center bg-[#002121] text-white hover:bg-[#8B2323] transition-all rounded-none border border-white/10 shadow-xl"
              >
                <X size={20} className="md:w-6 md:h-6" />
              </button>

              <div className="overflow-y-auto flex-1">
                {/* Hero Feature */}
                <div className="relative h-[250px] md:h-[500px] bg-[#f9f7f5]">
                  <img
                    src={selectedPost.image}
                    alt={selectedPost.title}
                    className="w-full h-full object-cover grayscale-[0.5] hover:grayscale-0 transition-all duration-1000"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-white via-white/20 to-transparent" />
                  
                  <div className="absolute bottom-6 left-6 right-6 md:bottom-12 md:left-12 md:right-12">
                     <div className="flex items-center gap-4 mb-4 md:mb-6">
                        <span className="w-8 md:w-10 h-px bg-[#965b32]" />
                        <span className="text-[#965b32] text-[9px] md:text-[10px] font-black tracking-[0.5em] uppercase">
                          Featured Insight
                        </span>
                     </div>
                     <h2 className="text-[28px] sm:text-4xl md:text-7xl font-sans font-bold text-[#002121] leading-[1.1] md:leading-[1.0] tracking-tighter max-w-4xl">
                        {selectedPost.title}
                     </h2>
                  </div>
                </div>

                <div className="px-6 md:px-24 pb-16 pt-8 md:pb-24 md:pt-16">
                   <div className="max-w-4xl">
                     <div className="flex flex-col sm:flex-row sm:flex-wrap gap-4 sm:gap-8 mb-10 md:mb-16 text-gray-400 text-[10px] font-bold tracking-[0.3em] uppercase border-y border-gray-100 py-6">
                        <div className="flex items-center gap-3">
                           <Calendar size={14} className="text-[#965b32]" />
                           {selectedPost.date}
                        </div>
                        <div className="flex items-center gap-3 md:border-l border-gray-200 md:pl-8">
                           <Clock size={14} className="text-[#965b32]" />
                           {selectedPost.readTime}
                        </div>
                        <div className="flex items-center gap-3 md:border-l border-gray-200 md:pl-8">
                           <MessageSquare size={14} className="text-[#965b32]" />
                           No Comments
                        </div>
                     </div>

                     <div className="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-12 lg:gap-20">
                        <div className="space-y-8 md:space-y-12 text-[#002121] text-lg md:text-2xl font-light leading-[1.7] md:leading-[1.6]">
                           {selectedPost.content.map((para, idx) => (
                              <p key={idx} className="first-letter:text-5xl first-letter:font-bold first-letter:float-left first-letter:mr-4 first-letter:mt-2 first-letter:text-[#965b32]">{para}</p>
                           )).reduce((acc: any, curr, idx) => idx === 0 ? [curr] : [...acc, <p key={`p-${idx}`} className="text-[#002121] text-lg md:text-2xl font-light leading-[1.7] md:leading-[1.6]">{selectedPost.content[idx]}</p>], [])}
                        </div>

                        {/* Author Sidebar */}
                        <div className="hidden lg:block">
                           <div className="sticky top-0 pt-4">
                              <div className="p-10 bg-[#f9f7f5] border-l-4 border-[#965b32]">
                                 <div className="w-16 h-16 bg-[#002121] text-white flex items-center justify-center text-xl font-bold mb-6">
                                    {selectedPost.author.split(' ').pop()?.charAt(0)}
                                 </div>
                                 <p className="text-[#965b32] text-[9px] font-black tracking-[0.3em] uppercase mb-2">Curator</p>
                                 <h4 className="text-[#002121] text-xl font-bold tracking-tight mb-4">{selectedPost.author}</h4>
                                 <p className="text-gray-500 text-xs font-light leading-relaxed mb-8">Specializing in the intersection of high-tech manufacturing and bespoke living environments.</p>
                                 <button className="w-full py-4 border border-[#002121] text-[#002121] text-[10px] font-black uppercase tracking-widest hover:bg-[#002121] hover:text-white transition-all">
                                    Follow Posts
                                 </button>
                              </div>
                           </div>
                        </div>
                     </div>
                   </div>
                </div>
              </div>

              {/* Action Bar */}
              <div className="bg-[#002121] p-6 md:p-10 flex flex-col md:flex-row items-center justify-between gap-6 md:gap-8">
                 <p className="text-white/40 text-[9px] md:text-[10px] font-bold tracking-[0.4em] md:tracking-[0.5em] uppercase text-center md:text-left">End of Insight ✦ TIQ Journal 2026</p>
                 <div className="flex flex-col sm:flex-row gap-4 w-full md:w-auto">
                    <button className="px-10 py-4 border border-white/20 text-white text-[11px] font-black uppercase tracking-widest hover:bg-white hover:text-[#002121] transition-all w-full sm:w-auto">
                       Share
                    </button>
                    <button 
                     onClick={closePost}
                     className="px-12 py-4 bg-[#d89a5b] text-white text-[11px] font-black uppercase tracking-widest hover:bg-white hover:text-[#002121] transition-all shadow-lg w-full sm:w-auto"
                    >
                      Close Journal
                    </button>
                 </div>
              </div>

            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Blog;
